services:

  postgres-for-backend:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sonsofturing
    volumes:
      - ../backend/databases:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sonsofturing"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sons_of_turing_net

  redis-for-backend:
    image: docker.io/redis:7
    restart: always
    # CHANGEME: row below to secure redis password
    command: >
      --requirepass myredissecret
      --maxmemory-policy noeviction
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - sons_of_turing_net

  qdrant-for-backend:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-for-sonsofturing
    environment:
      QDRANT__SERVICE__API_KEY=myqdrantsecret
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    networks:
      - sons_of_turing_net
    volumes:
      - ./qdrant_data:/qdrant/storage

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "16686:16686" # UI
  #     - "4319:4319"   # OTLP gRPC
  #     - "4320:4320"   # OTLP HTTP
  #   networks:
  #     - sons_of_turing_net

networks:
  sons_of_turing_net:
    driver: bridge

volumes:
  postgres-data:

configs:
  qdrant_config:
    content: |
      log_level: INFO