services:

  postgres-for-backend:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sonsofturing
    volumes:
      - ../backend/databases:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sonsofturing"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sons_of_turing_net

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "16686:16686" # UI
  #     - "4319:4319"   # OTLP gRPC
  #     - "4320:4320"   # OTLP HTTP
  #   networks:
  #     - sons_of_turing_net

networks:
  sons_of_turing_net:
    driver: bridge

volumes:
  postgres-data:
